//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PingPong7
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListaRankingowas
    {
        public int ListarankingowaId { get; set; }
        public int Punkty { get; set; }
        public int PlayerkId { get; set; }
    
        public virtual Zawodniks Zawodniks { get; set; }
    }
}
