//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PingPong7
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBaseEntities : DbContext
    {
        public DBaseEntities()
            : base("name=DBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Accounts> Accounts { get; set; }
        public virtual DbSet<ListaRankingowas> ListaRankingowas { get; set; }
        public virtual DbSet<Tabelas> Tabelas { get; set; }
        public virtual DbSet<Terminarzs> Terminarzs { get; set; }
        public virtual DbSet<Zawodniks> Zawodniks { get; set; }
        public virtual DbSet<Zespols> Zespols { get; set; }
    }
}
