//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PingPong7
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tabelas
    {
        public int TableId { get; set; }
        public int Rozegrano { get; set; }
        public int Wygrane { get; set; }
        public int Zremisowane { get; set; }
        public int Przegrane { get; set; }
        public int Punkty { get; set; }
        public string TeamName { get; set; }
    
        public virtual Zespols Zespols { get; set; }
    }
}
