//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PingPong7
{
    using System;
    using System.Collections.Generic;
    
    public partial class Terminarzs
    {
        public int Id_terminarz { get; set; }
        public string TeamName { get; set; }
        public string Wynik { get; set; }
        public string TeamName1 { get; set; }
    
        public virtual Zespols Zespols { get; set; }
    }
}
