//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PingPong7
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zawodniks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zawodniks()
        {
            this.ListaRankingowas = new HashSet<ListaRankingowas>();
        }
    
        public int PlayerkId { get; set; }
        public string Imie { get; set; }
        public string Nazwisko { get; set; }
        public int Wygrane { get; set; }
        public int Przegrane { get; set; }
        public string TeamName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListaRankingowas> ListaRankingowas { get; set; }
        public virtual Zespols Zespols { get; set; }
    }
}
